### ISSUE TITLE
Hier Reinschreiben um Rechte zu erhalten.

### ISSUE THREAD

**Issue by Alexander-Mauf** [Alexander-Mauf/HelpdeskLF6#3]
Hier einen Kommentar reinschreiben dann füge ich euch als Collaboratoren hinzu.

__Achtung:__
Ihr bekommt eine E-Mail in der ihr den Repo Zugang bestätigen müsst.

**Comment by felixwolff36** [comment]
Kredith(a)i

**Comment by metropas** [comment]
Pls add

**Comment by Alexander-Mauf** [comment]
@sidanke @felixwolff36 

invite is raus

**Comment by UnleqitPong** [comment]
Hi

**Comment by ErikWeissgerber** [comment]
Sehr geehrter Herr Mauf,

Ich bitte hiermit darum, als Collaborator  hinzugefügt zu werden.
Vielen Dank!

Mit Freundlichen Grüßen
Erik Weißgerber

**Comment by SilasJanssen** [comment]
bruh... Registrieren dauert viel zu lange

**Comment by mrogXTAIN** [comment]
X

**Comment by Autoradiowecker** [comment]
Hallo IT, 
bitte Rechte 
das sollte gestern schon fertig sein

**Comment by CLohrke** [comment]
It's me...

**Comment by Eiferius** [comment]
Halli Hallo, ich brauche Rechte

**Comment by Alexander-Mauf** [comment]
Seit 3 Monaten keine Anfragen -> geschlossen
