### ISSUE TITLE
Festplatte ist fast voll.  Ticket für Gruppe 4

### ISSUE THREAD

**Issue by Alexander-Mauf** [Alexander-Mauf/HelpdeskLF6#4]
Hallo meine Festplatte ist fast voll. 1 GB ist noch frei. Die Daten brauche ich weiterhin.

__Erstellt von:__
Markus, Simon, Alex
__Zu bearbeiten von:__
Gruppe 4

**Comment by ErikWeissgerber** [comment]
Benötigt: 

- neue Festplatte (mit mehr speicher als die alte Festplatte) 

TODO:

- [x] Clone alte Festplatte auf die neue 
- [x] Tausche die alte Festplatte durch die neue aus 
- [x] alte Festplatte vernichten oder für die Verwendung als ersatzteil formatieren
