### ISSUE TITLE
Leistungsstarkes Notebook und Lizenzzugang Gruppe 3

### ISSUE THREAD

**Issue by Alexander-Mauf** [Alexander-Mauf/HelpdeskLF6#7]
__Request:__
Besseres Notebook in alles.
Volle Adobe Cloud.
Office 365.

**Comment by mrogXTAIN** [comment]
Duplicate of #8

**Comment by SilasJanssen** [comment]
ich hab euch unsere Problem Anforderung in Issue 8 gestellt

**Comment by Alexander-Mauf** [comment]
Da wir alles in dem anderen machen können brauchen wir das nicht von jetzt an alle infos in #8
