### ISSUE TITLE
Neuer Grafik Laptop + Lizenzen (Problem von GR2)

### ISSUE THREAD

**Issue by SilasJanssen** [Alexander-Mauf/HelpdeskLF6#8]
__Anforderungen neuer Laptop:__

- [x] GTX 3080 Ti 
- [x] Intel Core-i7 12. Gen
- [x] 32 GB RAM
- [x] Dockingstation + 2 Ultra HD Bildschirme
- [x] BT Headset 
- [x] Maus & Tastatur (extra)
- [x] Graphic Pad
- [x] Office 365 & Adobe Creative Cloud

**Comment by metropas** [comment]
[jabra evolve2 65 Bluetooth Headset 140€](
https://www.amazon.de/Jabra-Evolve2-Wireless-Headset-Zertifizierte-Schwarz/dp/B086L72XSR)

**Comment by sidanke** [comment]
CHERRY KC 1000, Tastatur, Standard 12€

**Comment by sidanke** [comment]
CHERRY MC 1000 Maus, Schwarz 7€

**Comment by metropas** [comment]
[Huion Kamvas pro 16 (2.5k) Graphic Pad](https://store.huion.com/eu/products/kamvas-pro-16-2k?gclid=CjwKCAiA55mPBhBOEiwANmzoQhpo5NIIEiZYapLogPbyIGfg9-EnhoRxfKPLmCesn2bJayLDQuQANRoCZE8QAvD_BwE)
 
__Preis:__
599€

**Comment by Alexander-Mauf** [comment]
[Maus und tastatur als BT Version](https://www.amazon.de/CHERRY-Wireless-QWERTZ-Deutsch-Tastatur/dp/B073XGD26M/ref=sr_1_13?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2PD87UJODMCBC&keywords=CHERRY+KC+1000%2C+Tastatur%2C+Standard+12%E2%82%AC&s=ce-de&sprefix=cherry+kc+1000+tastatur+standard+12+%2Celectronics%2C84&sr=1-13) 

__Preis:__
44,99€

**Comment by Alexander-Mauf** [comment]
## Softwarezugänge: 


__Office 365 Versionskey:__

XXXXX-FFFFF-AAAAA-34HEJD-123AS-SASADSAD-ASDASDKJHFR

__Adobe Cloud:__

XASDGJ-AJDSA-OTUR-NBENM-AQQWOOP

**Comment by Alexander-Mauf** [comment]
### zusätzliche Monitore

[Dockingstation
](https://www.amazon.de/MOKiN-DisplayPort-unterst%C3%BCtzt-Kartenleser-Chromebook/dp/B08BRJD561/ref=sr_1_6?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1XRBOQD2KVJ&keywords=Dockingstation+Monitor+displayport&s=ce-de&sprefix=dockingstation+monitor+displayport%2Celectronics%2C61&sr=1-6) 49,99€

[Monitore](https://www.amazon.de/Samsung-U28E590D-Monitor-Reaktionszeit-Aktualisierungsrate/dp/B08SWFP37W/ref=sr_1_4?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1VHHWM7Z7ARAG&keywords=ultra+hd+monitor&s=ce-de&sprefix=ultrahd+monito%2Celectronics%2C79&sr=1-4)
225,00€ * 2

**Comment by Alexander-Mauf** [comment]
[Razer Blade 15](https://www.razer.com/de-de/gaming-laptops/razer-blade)

upgrade auf i9
~3500€

**Comment by Alexander-Mauf** [comment]
__Kostenübersicht:__
 3500€ Laptop

+ 500€ Monitore
+ 2000€ Software
+ 190€ Peripherie 
+ 599€ Graphic Pad

~6800€

**Comment by Alexander-Mauf** [comment]
Ausstehend Gespräch mit Buchhaltung ob die Summe freigegeben werden kann.

**Comment by Alexander-Mauf** [comment]
Thematik ist durch LF6 macht jetzt was anderes.
